# example workflow for Coverity on Polaris
name: coverity-on-polaris
on:
  push:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  coverity-on-polaris:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Polaris Scan
      env:
        POLARIS_SERVER_URL: ${{ vars.POLARIS_SERVER_URL }}
        POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
      run: |
        curl -fLsS -o polaris.zip $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
        unzip -d $RUNNER_TEMP -jo polaris.zip && rm -f polaris.zip
        $RUNNER_TEMP/polaris --co project.name=chuckaude-${{ github.event.repository.name }} analyze -w
    - name: Save Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: polaris-cli-logs
        path: ${{ github.workspace }}/.synopsys
